// GENERATED by scripts/generate-pwa-assets.mjs — do not edit by hand.
// iOS PWA splash screens. Spread into the root route's head links.

export const appleSplashLinks: ReadonlyArray<{
  rel: 'apple-touch-startup-image'
  media: string
  href: string
}> = [
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-2048x2732.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-1668x2388.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-1640x2360.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-1668x2224.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-1620x2160.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-1536x2048.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-1488x2266.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1320x2868.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1206x2622.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1290x2796.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1179x2556.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1170x2532.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1284x2778.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1242x2688.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1125x2436.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-828x1792.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)',
    href: '/apple-splash-portrait-1242x2208.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-750x1334.png',
  },
  {
    rel: 'apple-touch-startup-image',
    media:
      'screen and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)',
    href: '/apple-splash-portrait-640x1136.png',
  },
]
