/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/': typeof ApiHealthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health': typeof ApiHealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/': typeof ApiHealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/health/live' | '/api/health/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health/live' | '/api/health'
  id: '__root__' | '/' | '/api/health/live' | '/api/health/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
